version: "3.9"

services:
  web:
    image: nginx:stable
    ports:
      - "4933:80"
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
